version: 0.3
domains:

  clinical_operations:
    name: "Clinical Operations"
    description: "EHR data, patient care, clinical workflows, and provider operations"
    keywords: ["ehr", "emr", "patient", "provider", "physician", "nurse", "clinical", "diagnosis", "procedure", "treatment", "care", "medical", "health", "hospital", "clinic", "encounter", "visit", "admission", "discharge", "order", "medication", "lab", "imaging", "vital", "observation", "note", "mrn"]
    subdomains:
      patient_care:
        name: "Patient Care & Treatment"
        description: "Patient data, encounters, diagnoses, procedures, medications, orders"
        keywords: ["patient", "encounter", "visit", "admission", "diagnosis", "procedure", "medication", "order", "treatment", "therapy", "demographic", "mrn", "icd", "cpt", "prescription", "discharge"]
      
      clinical_results:
        name: "Clinical Results & Diagnostics"
        description: "Lab results, imaging, pathology, test results, observations"
        keywords: ["lab", "laboratory", "test", "result", "imaging", "radiology", "pathology", "xray", "ct", "mri", "loinc", "observation", "vital", "specimen", "panel", "scan"]
      
      clinical_documentation:
        name: "Clinical Documentation"
        description: "Clinical notes, assessments, care plans, documentation"
        keywords: ["note", "documentation", "narrative", "assessment", "plan", "progress", "discharge_summary", "consultation", "dictation", "care_plan", "free_text"]

  payer_operations:
    name: "Payer Operations"
    description: "Health insurance, claims, member management, and care coordination"
    keywords: ["payer", "insurance", "claim", "member", "enrollment", "benefit", "coverage", "plan", "premium", "copay", "deductible", "authorization", "utilization", "network", "provider", "reimbursement", "adjudication", "eligibility"]
    subdomains:
      membership_benefits:
        name: "Membership & Benefits"
        description: "Member enrollment, eligibility, benefits, coverage, plan management"
        keywords: ["member", "enrollment", "eligibility", "subscriber", "benefit", "coverage", "plan", "formulary", "copay", "deductible", "network", "effective_date"]
      
      claims_processing:
        name: "Claims Processing"
        description: "Claims submission, adjudication, payment, denials, appeals"
        keywords: ["claim", "adjudication", "payment", "reimbursement", "denial", "appeal", "remittance", "eob", "837", "835", "hcfa", "ub04", "adjustment"]
      
      care_management:
        name: "Care & Utilization Management"
        description: "Prior authorization, utilization review, case management, care coordination"
        keywords: ["prior_authorization", "utilization", "case_management", "care_coordination", "medical_necessity", "preauth", "utilization_review", "disease_management"]

  pharmaceutical:
    name: "Pharmaceutical Operations"
    description: "Drug development, clinical trials, manufacturing, and commercial operations"
    keywords: ["pharma", "pharmaceutical", "drug", "compound", "clinical_trial", "study", "protocol", "manufacturing", "batch", "regulatory", "fda", "commercial", "safety", "adverse_event"]
    subdomains:
      clinical_development:
        name: "Clinical Development"
        description: "Clinical trials, studies, research, adverse events, regulatory submissions"
        keywords: ["clinical_trial", "study", "protocol", "subject", "site", "crf", "adverse_event", "efficacy", "safety", "regulatory", "submission", "ctms", "edc"]
      
      manufacturing_supply:
        name: "Manufacturing & Supply Chain"
        description: "Drug manufacturing, quality, batch records, distribution, inventory"
        keywords: ["manufacturing", "batch", "lot", "quality", "gmp", "production", "supply_chain", "distribution", "inventory", "stability", "deviation"]
      
      commercial_medical:
        name: "Commercial & Medical Affairs"
        description: "Sales operations, marketing, medical information, HCP engagement"
        keywords: ["commercial", "sales", "marketing", "hcp", "rep", "territory", "medical_affairs", "msl", "publication", "medical_information"]

  quality_outcomes:
    name: "Quality & Patient Outcomes"
    description: "Quality measures, patient outcomes, safety, experience, and population health"
    keywords: ["quality", "outcome", "measure", "patient_safety", "experience", "satisfaction", "mortality", "complication", "readmission", "hedis", "star", "population_health", "risk", "registry"]
    subdomains:
      clinical_quality:
        name: "Clinical Quality & Safety"
        description: "Quality measures, outcomes, safety events, performance metrics"
        keywords: ["quality", "outcome", "safety", "mortality", "complication", "readmission", "infection", "measure", "hedis", "star", "mips", "benchmark"]
      
      patient_experience:
        name: "Patient Experience & Engagement"
        description: "Patient satisfaction, experience, feedback, engagement, portal usage"
        keywords: ["experience", "satisfaction", "survey", "hcahps", "feedback", "engagement", "portal", "patient_reported", "adherence", "activation"]
      
      population_health:
        name: "Population Health Management"
        description: "Population health, risk stratification, care gaps, preventive care, SDOH"
        keywords: ["population_health", "risk_stratification", "care_gap", "preventive", "screening", "chronic_disease", "sdoh", "social_determinants", "community_health"]

  revenue_cycle:
    name: "Revenue Cycle"
    description: "Healthcare billing, coding, collections, and financial operations"
    keywords: ["revenue_cycle", "billing", "charge", "coding", "collection", "payment", "denial", "ar", "accounts_receivable", "claim", "reimbursement", "charge_master", "cpt", "icd", "drg"]
    subdomains:
      billing_coding:
        name: "Billing & Coding"
        description: "Charge capture, coding, charge master, billing, invoicing"
        keywords: ["billing", "charge", "coding", "charge_master", "cdm", "cpt", "icd", "drg", "invoice", "claim_submission", "scrubbing"]
      
      collections_ar:
        name: "Collections & AR Management"
        description: "Payment posting, collections, denials, appeals, accounts receivable"
        keywords: ["collection", "payment", "ar", "accounts_receivable", "denial", "appeal", "aging", "bad_debt", "follow_up", "adjustment"]
      
      contract_reimbursement:
        name: "Contracts & Reimbursement"
        description: "Payer contracts, fee schedules, reimbursement rates, variance analysis"
        keywords: ["contract", "payer", "fee_schedule", "reimbursement", "rate", "allowable", "underpayment", "variance"]

  precision_medicine:
    name: "Precision Medicine & Research"
    description: "Genomics, biomarkers, precision medicine, clinical research, real-world evidence"
    keywords: ["genomics", "genetics", "biomarker", "precision", "personalized", "research", "real_world", "rwe", "observational", "sequencing", "variant", "molecular", "pharmacogenomics"]
    subdomains:
      genomics_molecular:
        name: "Genomics & Molecular Data"
        description: "Genomic sequencing, variants, biomarkers, molecular profiling"
        keywords: ["genomics", "sequencing", "variant", "mutation", "biomarker", "molecular", "ngs", "vcf", "gene", "expression", "oncology", "pharmacogenomics"]
      
      clinical_research:
        name: "Clinical Research & RWE"
        description: "Observational studies, registries, real-world data, outcomes research"
        keywords: ["research", "real_world", "rwe", "observational", "registry", "cohort", "outcomes_research", "epidemiology", "health_economics", "heor"]

  medical_devices:
    name: "Medical Devices & Equipment"
    description: "Medical devices, IoMT, equipment management, device data"
    keywords: ["device", "equipment", "iomt", "wearable", "sensor", "monitor", "implant", "asset", "maintenance", "udi", "telemetry", "connected"]
    subdomains:
      device_data:
        name: "Device Data & Monitoring"
        description: "Connected device data, remote monitoring, IoMT, telemetry, sensor data"
        keywords: ["device_data", "iomt", "connected", "remote_monitoring", "telemetry", "sensor", "wearable", "real_time", "streaming"]
      
      asset_management:
        name: "Asset & Equipment Management"
        description: "Equipment inventory, maintenance, calibration, asset tracking, UDI registry"
        keywords: ["equipment", "asset", "inventory", "maintenance", "calibration", "tracking", "udi", "implant", "registry", "recall"]

  finance:
    name: "Finance"
    description: "Financial data, transactions, accounting, and related business metrics"
    keywords: ["revenue", "transaction", "payment", "invoice", "billing", "accounting", "financial", "cost", "budget", "profit", "loss", "balance", "ledger", "asset", "liability", "equity", "cash", "credit", "debit", "tax", "audit"]
    subdomains:
      accounting:
        name: "Accounting"
        description: "General ledger, accounts payable/receivable, financial statements"
        keywords: ["ledger", "journal", "account", "balance", "trial_balance", "gl", "ap", "ar", "financial_statement"]
      
      payments:
        name: "Payments"
        description: "Payment processing, transactions, billing"
        keywords: ["payment", "transaction", "billing", "invoice", "receipt", "charge", "refund", "settlement"]
      
      treasury:
        name: "Treasury"
        description: "Cash management, investments, banking"
        keywords: ["cash", "bank", "investment", "treasury", "liquidity", "funding", "capital"]
      
      compliance:
        name: "Compliance"
        description: "Regulatory compliance, audit, tax reporting"
        keywords: ["audit", "compliance", "regulatory", "tax", "sox", "gaap", "ifrs", "regulation"]

  crm:
    name: "Customer Relationship Management"
    description: "Customer data, interactions, sales, and relationship management"
    keywords: ["customer", "contact", "lead", "opportunity", "sales", "prospect", "account", "relationship", "interaction", "communication", "campaign", "pipeline", "deal", "quote", "contract"]
    subdomains:
      sales:
        name: "Sales"
        description: "Sales processes, opportunities, quotes, deals"
        keywords: ["sales", "opportunity", "quote", "deal", "pipeline", "forecast", "territory", "commission"]
      
      marketing:
        name: "Marketing"
        description: "Marketing campaigns, leads, attribution"
        keywords: ["marketing", "campaign", "lead", "attribution", "segment", "channel", "promotion", "email", "social"]
      
      support:
        name: "Customer Support"
        description: "Customer service, tickets, support interactions"
        keywords: ["support", "ticket", "case", "issue", "resolution", "help", "service", "complaint", "escalation"]
      
      loyalty:
        name: "Customer Loyalty"
        description: "Loyalty programs, rewards, retention"
        keywords: ["loyalty", "reward", "point", "retention", "churn", "lifetime_value", "engagement"]

  hr:
    name: "Human Resources"
    description: "Employee data, payroll, benefits, and HR processes"
    keywords: ["employee", "staff", "personnel", "payroll", "salary", "wage", "benefit", "hr", "human_resources", "workforce", "talent", "recruitment", "performance", "training", "leave", "time", "attendance"]
    subdomains:
      payroll:
        name: "Payroll"
        description: "Employee compensation, salary, benefits"
        keywords: ["payroll", "salary", "wage", "compensation", "bonus", "commission", "deduction", "tax_withholding"]
      
      recruitment:
        name: "Recruitment"
        description: "Hiring, candidates, job applications"
        keywords: ["recruitment", "hiring", "candidate", "application", "interview", "job", "position", "vacancy"]
      
      performance:
        name: "Performance Management"
        description: "Employee performance, reviews, goals"
        keywords: ["performance", "review", "goal", "objective", "appraisal", "feedback", "rating", "development"]
      
      benefits:
        name: "Benefits & Compensation"
        description: "Employee benefits, insurance, retirement"
        keywords: ["benefit", "insurance", "retirement", "401k", "health", "dental", "vision", "pto", "vacation"]

  operations:
    name: "Operations"
    description: "Operational data, supply chain, inventory, and logistics"
    keywords: ["inventory", "supply", "chain", "logistics", "warehouse", "shipment", "order", "fulfillment", "procurement", "vendor", "supplier", "product", "manufacturing", "production", "quality", "facility", "asset", "maintenance"]
    subdomains:
      inventory:
        name: "Inventory Management"
        description: "Stock levels, inventory tracking, warehouse management"
        keywords: ["inventory", "stock", "warehouse", "storage", "sku", "item", "location", "bin", "cycle_count"]
      
      procurement:
        name: "Procurement"
        description: "Purchasing, suppliers, vendor management"
        keywords: ["procurement", "purchase", "vendor", "supplier", "contract", "rfp", "po", "requisition"]
      
      logistics:
        name: "Logistics"
        description: "Shipping, delivery, transportation"
        keywords: ["logistics", "shipping", "delivery", "transport", "carrier", "tracking", "freight", "route"]
      
      manufacturing:
        name: "Manufacturing"
        description: "Production, quality control, manufacturing processes"
        keywords: ["manufacturing", "production", "quality", "batch", "lot", "work_order", "bom", "routing"]

  marketing:
    name: "Marketing"
    description: "Marketing campaigns, digital marketing, brand management"
    keywords: ["marketing", "campaign", "brand", "advertisement", "promotion", "digital", "social", "email", "content", "seo", "sem", "analytics", "attribution", "conversion", "engagement", "reach", "impression", "click"]
    subdomains:
      digital:
        name: "Digital Marketing"
        description: "Online marketing, social media, email campaigns"
        keywords: ["digital", "online", "social", "email", "web", "mobile", "app", "seo", "sem", "ppc"]
      
      analytics:
        name: "Marketing Analytics"
        description: "Marketing performance, attribution, ROI analysis"
        keywords: ["analytics", "attribution", "roi", "conversion", "funnel", "cohort", "retention", "engagement"]
      
      content:
        name: "Content Management"
        description: "Content creation, management, and distribution"
        keywords: ["content", "blog", "article", "video", "image", "asset", "publication", "editorial"]

  product:
    name: "Product"
    description: "Product data, features, user interactions, and product analytics"
    keywords: ["product", "feature", "user", "usage", "interaction", "behavior", "session", "click", "view", "conversion", "funnel", "cohort", "retention", "engagement", "feedback", "rating", "review"]
    subdomains:
      analytics:
        name: "Product Analytics"
        description: "User behavior, feature usage, product metrics"
        keywords: ["analytics", "behavior", "usage", "metric", "kpi", "funnel", "cohort", "retention"]
      
      feedback:
        name: "Product Feedback"
        description: "User feedback, reviews, ratings, surveys"
        keywords: ["feedback", "review", "rating", "survey", "nps", "satisfaction", "comment", "suggestion"]
      
      catalog:
        name: "Product Catalog"
        description: "Product information, SKUs, categories, attributes"
        keywords: ["catalog", "sku", "product", "category", "attribute", "specification", "variant", "bundle"]

  technology:
    name: "Technology"
    description: "System data, infrastructure, security, and IT operations"
    keywords: ["system", "infrastructure", "security", "log", "event", "monitoring", "performance", "server", "application", "database", "network", "cloud", "deployment", "configuration", "alert", "incident"]
    subdomains:
      security:
        name: "Security"
        description: "Security logs, access control, threat detection"
        keywords: ["security", "access", "permission", "auth", "login", "threat", "vulnerability", "incident", "breach"]
      
      monitoring:
        name: "System Monitoring"
        description: "System performance, logs, alerts, uptime"
        keywords: ["monitoring", "performance", "log", "alert", "uptime", "metric", "health", "status"]
      
      infrastructure:
        name: "Infrastructure"
        description: "Servers, networks, cloud resources, configurations"
        keywords: ["infrastructure", "server", "network", "cloud", "instance", "resource", "configuration", "deployment"]

  legal:
    name: "Legal"
    description: "Legal documents, contracts, compliance, and regulatory data"
    keywords: ["legal", "contract", "agreement", "compliance", "regulatory", "policy", "terms", "condition", "liability", "intellectual_property", "patent", "trademark", "copyright", "litigation", "dispute"]
    subdomains:
      contracts:
        name: "Contracts"
        description: "Legal contracts, agreements, terms"
        keywords: ["contract", "agreement", "terms", "condition", "clause", "amendment", "renewal", "termination"]
      
      compliance:
        name: "Regulatory Compliance"
        description: "Compliance tracking, regulatory requirements"
        keywords: ["compliance", "regulatory", "requirement", "audit", "violation", "penalty", "reporting"]
      
      intellectual_property:
        name: "Intellectual Property"
        description: "Patents, trademarks, copyrights, IP management"
        keywords: ["patent", "trademark", "copyright", "ip", "intellectual_property", "license", "royalty"]

  data:
    name: "Data & Analytics"
    description: "Data management, analytics, reporting, and business intelligence"
    keywords: ["data", "analytics", "report", "dashboard", "kpi", "metric", "dimension", "measure", "fact", "warehouse", "mart", "etl", "pipeline", "quality", "lineage", "governance", "master", "reference"]
    subdomains:
      warehouse:
        name: "Data Warehouse"
        description: "Data warehouse tables, dimensions, facts"
        keywords: ["warehouse", "dimension", "fact", "star", "snowflake", "cube", "mart", "summary"]
      
      pipeline:
        name: "Data Pipeline"
        description: "ETL processes, data integration, pipeline management"
        keywords: ["etl", "pipeline", "integration", "transform", "load", "batch", "stream", "schedule"]
      
      governance:
        name: "Data Governance"
        description: "Data quality, lineage, metadata management"
        keywords: ["governance", "quality", "lineage", "metadata", "catalog", "dictionary", "standard", "policy"]