"""Tiered ontology index loader for large published ontologies.

Supports three tiers of increasing detail for both entities and edges,
enabling iterative LLM-based classification without exceeding context windows.
"""

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

logger = logging.getLogger(__name__)


class OntologyIndexLoader:
    """Loads tiered YAML indexes for three-pass ontology prediction.
    
    Tier files are generated by scripts/build_ontology_indexes.py from
    published ontologies (FHIR R4, OMOP CDM, Schema.org). They live in
    a subdirectory named after the bundle alongside the main bundle YAML.
    """

    def __init__(self, bundle_name: str = "healthcare", base_dir: Optional[str] = None):
        if base_dir:
            self._bundle_dir = Path(base_dir)
        else:
            pkg_root = Path(__file__).resolve().parent.parent.parent
            self._bundle_dir = pkg_root / "configurations" / "ontology_bundles" / bundle_name
        self._cache: Dict[str, Any] = {}

    @property
    def has_tier_indexes(self) -> bool:
        """Check whether tier index files exist for this bundle."""
        return (self._bundle_dir / "entities_tier1.yaml").is_file()

    def _load(self, filename: str) -> Any:
        if filename not in self._cache:
            path = self._bundle_dir / filename
            if not path.is_file():
                logger.debug("Tier file not found: %s", path)
                self._cache[filename] = None
                return None
            self._cache[filename] = yaml.safe_load(path.read_text(encoding="utf-8"))
        return self._cache[filename]

    # --- Entity tiers ---

    def get_entities_tier1(self) -> List[Dict[str, str]]:
        """Tier 1: compact list of {name, description} for broad screening."""
        return self._load("entities_tier1.yaml") or []

    def get_entities_tier2_scoped(self, entity_names: List[str]) -> Dict[str, Any]:
        """Tier 2: scoped detail for named entities only (source, URI, parent, edges capped at 8)."""
        full = self._load("entities_tier2.yaml")
        if not full:
            return {}
        return {k: full[k] for k in entity_names if k in full}

    def get_entities_tier3_scoped(self, entity_names: List[str]) -> Dict[str, Any]:
        """Tier 3: full profiles for final deep classification."""
        full = self._load("entities_tier3.yaml")
        if not full:
            return {}
        return {k: full[k] for k in entity_names if k in full}

    # --- Edge tiers ---

    def get_edges_tier1(self) -> List[Dict[str, str]]:
        """Tier 1: compact edge list with name, domain, range."""
        return self._load("edges_tier1.yaml") or []

    def get_edges_tier2_scoped(self, edge_names: List[str]) -> Dict[str, Any]:
        """Tier 2: scoped edge detail."""
        full = self._load("edges_tier2.yaml")
        if not full:
            return {}
        return {k: full[k] for k in edge_names if k in full}

    def get_edges_tier3_scoped(self, edge_names: List[str]) -> Dict[str, Any]:
        """Tier 3: full edge profiles with URIs."""
        full = self._load("edges_tier3.yaml")
        if not full:
            return {}
        return {k: full[k] for k in edge_names if k in full}

    # --- URI lookup ---

    def get_uri(self, entity_name: str) -> Optional[str]:
        """Look up the owl:equivalentClass URI for an entity."""
        uris = self._load("equivalent_class_uris.yaml")
        if not uris:
            return None
        return uris.get(entity_name)

    def get_all_uris(self) -> Dict[str, str]:
        """Return the full entity_name -> URI mapping."""
        return self._load("equivalent_class_uris.yaml") or {}

    def entity_count(self) -> int:
        """Number of entities available in tier 1."""
        return len(self.get_entities_tier1())
